[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter = "399X13x4QfGDV9SFyo76zdCXxXXkuxujyoPqDetrL4Mb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/zoid/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
